Added file content view.
cuibus/RepoViewer pull request #12
Opened 2021-04-03 16:32 UTC by enyedi-ervin-30126

2021-04-04 05:48 UTC, cuibus requested changes

2021-04-04 05:48 UTC, cuibus commented on src/main/java/utcn/repoviewer/FileView.java
> +
code cosmetics: delete empty line here

2021-04-04 05:48 UTC, cuibus commented on src/main/java/utcn/repoviewer/FileView.java
> +    public String modifyPath(String absolutePath){
Why do we need this method anyway ? The path of the absolute file should be ready when the FileView object is created. While debugging, I discovered that the path received from Main looks like this:
![image](https://user-images.githubusercontent.com/57090049/113499799-8bfcec00-9521-11eb-819f-ee8d53f8dc9c.png)
This is a bug which might have been introduced by a member of the team, but you must fix this before adding unnecessary code in the FileView.
I'd say there are 2 options:
1. You either get the absolute path of the file directly from Main (it is fully computed there)
2. You get base path, student name, and relative path of the file and you compute the absolute path here.

2021-04-04 09:33 UTC, enyedi-ervin-30126 commented on src/main/java/utcn/repoviewer/FileView.java
> +    public String modifyPath(String absolutePath){
I discovered that the incorrect path is returned by a method which can not be modified. 
`String firstSelectedPath = treeFolders.getSelectionPath().toString();`
The getSelectionPath() returns the path incorrectly in Main. 

Should I modify the path which is sent to the FileView constructor here? I could not understand how should I implement the second option which you have suggested.

2021-04-04 15:11 UTC, cuibus commented on src/main/java/utcn/repoviewer/FileView.java
> +    public String modifyPath(String absolutePath){
Indeed, if you take the selection path you get a TreePath object. If you call .toString() immediately on that object, you get a string which contains three parts. I'm guessing you only need the second and third part from that object.

2021-04-06 16:44 UTC, cuibus requested changes
We can check the merging of this branch together, it's going to be a bit complicated because @nicorici-iulia-cristina-30126 also worked on the FileView.

2021-04-06 16:44 UTC, cuibus commented on src/main/java/utcn/repoviewer/FileView.java
> +        }
Why do we disable the textAreaCode on condition ? The textAreaCode should not be editable in any case.

2021-04-06 18:44 UTC, enyedi-ervin-30126 commented on src/main/java/utcn/repoviewer/FileView.java
> +        }
The ticked said that if there is no file with the same name, the area should be grayed out.

2021-04-07 05:00 UTC, cuibus approved these changes

2021-04-07 11:24 UTC, cuibus approved these changes

2021-04-07 11:24 UTC, merged