Done implementing feedback facilities
cuibus/RepoViewer pull request #22
Opened 2021-04-12 11:24 UTC by ceoca-ovidiu-30126

2021-04-12 20:32 UTC, cuibus requested changes

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FeedbackManagement.java
> +    private static List<JButton> emailButtonsList = new ArrayList<>();
Is this still needed ? It seems you moved all the UI functionality to the FileView.

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FeedbackManagement.java
> +    public void addButton(FeedbackEnum type, JButton button) {
This method is not needed

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FeedbackManagement.java
> +    }
These methods are not needed

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FeedbackManagement.java
> +    public static void createAndWriteFile(String studentName, String message) {
It seems like what you need is an append functionality. Please rename this method to something like "appendLineToFileForStudent" and make sure you don't reinvent the wheel, please check documentation [here](https://docs.oracle.com/javase/7/docs/api/java/io/FileWriter.html#FileWriter(java.io.File,%20boolean))
Methods createFile() and writeToFile() can now be replaced by this append method.

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FeedbackManagement.java
> +
This new line at the beginning of a method is not needed. Please remove it throughout the code.

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FeedbackManagement.java
> +
Please remove this empty line

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FileView.java
> +        // MY CODE
please delete this comment. Once it is merged into main, a comment that says "my code" won't help anyone since we don't know who added that code just by looking at it.

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FileView.java
> +        JButton buttonGood = createButton("", Color.decode("#52b788"), new ImageIcon("D:\\RepoViewer\\RepoViewer\\src\\res\\like.png"), "goodButton" + studentName, goodButtonActionListener(studentNam
1. never ever use absolute paths in a project. You don't know who uses it and where it will be installed on their machine.
2. Also, there exists a folder ./src/main/resources. Please either use that folder to place the *.png files or move the contents from there to your ./src/res folder.

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FileView.java
> +    public String getFileContents(String absolutePath) {
Please rename this method to "getTextFileContents"

2021-04-12 20:32 UTC, cuibus commented on src/main/java/utcn/repoviewer/FileView.java
> +        for (String types : allowedImageTypes) {
Thanks for taking care of alignment!

2021-04-14 05:44 UTC, cuibus commented on src/main/java/utcn/repoviewer/FeedbackManagement.java
> +
Also, please note that the path for one lab session is not always isp-lab-X-main (see lab7 and lab8). I think it's better to assume that what comes after the student name and group is the correct relative path:
popescu-ion-30135/_isp-lab-5-main/src/main/..._
popescu-ion-30135/_lab-isp-2021/pom.xml_

2021-04-14 15:37 UTC, ceoca-ovidiu-30126 commented on src/main/java/utcn/repoviewer/FeedbackManagement.java
> +
I also thought about this problem once when I looked in my repo. I changed the method and now it returns the path based on the last 5 characters from studentName which represent the group of the student. The algorithm search for the student group in the whole path of the file. After finding it, it returns the position of start. Giving the fact that all groups have a number made out of 5 digits, the start position for the evaluated file will be 6 because we do need a "\" at the start of the path.
![picture ](https://user-images.githubusercontent.com/79502686/114738186-6b6a3880-9d50-11eb-8582-7015208be717.png)

2021-04-14 15:56 UTC, cuibus approved these changes

2021-04-14 15:56 UTC, cuibus commented on pom.xml
> +        </dependency>
this dependency already exists in the project -> see above

2021-04-14 15:56 UTC, merged