Done implementing send email to students feature
cuibus/RepoViewer pull request #23
Opened 2021-04-26 15:30 UTC by ceoca-ovidiu-30126

This push contains the implementation of sending emails which contains a feedback file to each student. I left a comment on purpose after each call of sendEmail() method in main just in case we will need that in the future to test send email functionality. That line of code can be deleted without any problem.

2021-04-27 05:46 UTC, cuibus requested changes

2021-04-27 05:46 UTC, cuibus commented on src/main/java/utcn/repoviewer/Main.java
> +                            if (student.contains(studentInformation.name.toLowerCase()) && student.contains(studentInformation.surname.toLowerCase()) && student.contains(studentInformation.groupId))
Here we must be very careful with searching for students in the list (we might send the email to the wrong recipient). There have been many cases of students with similar or really identical names in the same group. Moreover, calling the **contains()** for the case "Popescu Ionut" and "Pop Ion" will wrongly identify the student.
Another argument is that we don't know if in the future we will have the same structure of the info file.
In any case, this program views repos, and it is better to search for emails by repository link, because that is surely unique (git won't accept two identical usernames, and the repo link is bound on that username). The repo link is of the form:
https://github.com/isp-cluj/isp-labs-main-Pop-Vasile-Ion-30126

2021-04-27 05:46 UTC, cuibus commented on src/main/java/utcn/repoviewer/Main.java
> +                            new StudentManager().sendEmail(fromEmail, password, toEmail, emailBodyString, filePath);
why build a StudentManager object each time we send an email ? Make sendEmail() static.

2021-04-27 05:46 UTC, cuibus commented on src/main/java/utcn/repoviewer/Main.java
> +        File f = new File("src\\main\\students files");
as stated above, the path should be a constant somewhere in the program

2021-04-27 05:46 UTC, cuibus commented on src/main/java/utcn/repoviewer/StudentManager.java
> +    public static final boolean DoSendEmails = false;
you must test this attribute when sending the email. Wrap an **if(DoSendEmails)** around the **Transport.send(message);** statement.

2021-04-27 05:46 UTC, cuibus commented on src/main/java/utcn/repoviewer/Main.java
> +            ArrayList<StudentInformation> studentInformations = new StudentManager().getStudentsInformation();
maybe add a method **GetEmailForRepo( )** in **StudentManagement** class and call that method here and in **buttonSendAllEmailsActionPerformed( )** method. Do not duplicate code.

2021-04-27 05:46 UTC, cuibus commented on src/main/java/utcn/repoviewer/FeedbackManagement.java
>          String fileName = studentName + ".txt";
create a GetFilenameForStudent() method that returns the filename. There are many places in the program where you will use this. If at some point we decide to change something there (for example, the filename or extension), it's easier to modify.

2021-04-27 05:46 UTC, cuibus commented on nbactions.xml
> +<?xml version="1.0" encoding="UTF-8"?>
this file should be git ignored

2021-04-27 19:49 UTC, cuibus requested changes

2021-04-27 19:49 UTC, cuibus commented on .gitignore
> +.xml
hmm, not a good idea to ignore all .xml files. We still need to push to pom.xml. Just ignore the single .xml file generated by netbeans.

2021-04-27 19:49 UTC, cuibus commented on src/main/java/utcn/repoviewer/Main.java
> +        jScrollPane3 = new javax.swing.JScrollPane();
please rename this to jScrollPaneEmail

2021-04-27 19:49 UTC, cuibus commented on src/main/java/utcn/repoviewer/Main.java
> +    private static final String studentsFolderPath = "src\\main\\students files";
Why do we have another variable for this path ? It should be taken from FeedbackManagement, where attribute **studentsFilesDirectoryPath** should be public

2021-04-27 19:49 UTC, cuibus commented on src/main/java/utcn/repoviewer/StudentManager.java
> +            if (studentInformation.repoLink.substring(14, studentInformation.repoLink.length()).equals(studentName)) {
Good for now, but we might have to change this in the future. We don't know what the naming structure of the repo will be in the future.
As an idea, string processings like these are generally done with regular expressions (regex). You might want to have a look into that when you have the time.

2021-04-28 06:10 UTC, ceoca-ovidiu-30126 commented on src/main/java/utcn/repoviewer/StudentManager.java
> +            if (studentInformation.repoLink.substring(14, studentInformation.repoLink.length()).equals(studentName)) {
I found an online regex generator that seems to work just fine ( https://regex-generator.olafneumann.org/ ). Based on the example above ( https://github.com/isp-cluj/isp-labs-main-Pop-Vasile-Ion-30126 ) I managed to get a regex that looks like this ( ^[a-zA-Z]+:/-[a-zA-Z]+\.[a-zA-Z]+/([a-zA-Z]+(-[a-zA-Z]+)+)/isp-labs-main-[a-zA-Z]+-[a-zA-Z]+-[a-zA-Z]+-[0-9]+$ ) but I do not know exactly how to find a specific repo to get the mail from based on this expression. I think that all repos will match this regex because all repos looks the same.

However, I tried another approach of this problem.

    public static String getEmailForRepo(String studentName) {
        for (StudentInformation studentInformation : studentsInformation) {
            if (studentInformation.repoLink.indexOf(studentName) != -1) {
                return studentInformation.emailAddress;
            }
        }
        System.out.println("The mail could not be found ");
        return "";
     }

Giving the fact that each repo has just one name in it, I search through them and if I found the repo that contains the name of the student, I return the email. In this case, I think that we do not need to know the structure of the repo because the method looks only for the first names.

I also tested this method and it seems to work ( I wanted to send an email to pop-ionut-30123 ):

![1](https://user-images.githubusercontent.com/79502686/116354558-46220380-a801-11eb-88ba-89f3978c8d61.png)

2021-04-28 06:18 UTC, ceoca-ovidiu-30126 commented on src/main/java/utcn/repoviewer/Main.java
> +        jScrollPane3 = new javax.swing.JScrollPane();
The code above is generated by NetBeans and I cannot modify it. 

![3](https://user-images.githubusercontent.com/79502686/116355498-9baae000-a802-11eb-87af-43cb8ea6e20d.png)

2021-04-28 07:36 UTC, cuibus commented on src/main/java/utcn/repoviewer/Main.java
> +        jScrollPane3 = new javax.swing.JScrollPane();
Ok, then leave it as it is for the moment.

2021-04-28 07:42 UTC, cuibus commented on src/main/java/utcn/repoviewer/StudentManager.java
> +            if (studentInformation.repoLink.substring(14, studentInformation.repoLink.length()).equals(studentName)) {
I like the second approach. Let's use that for now instead of the regex.

2021-04-29 06:46 UTC, cuibus approved these changes

2021-04-29 06:46 UTC, merged