Added feedback for comments; added markers for students with comments…
cuibus/RepoViewer pull request #31
Opened 2021-08-04 11:58 UTC by adelinb

… and sent emails

2021-08-04 20:17 UTC, cuibus requested changes

2021-08-04 20:17 UTC, cuibus commented on src/main/java/utcn/repoviewer/MainWindow.java
> +                // studentsList.addElement(studentFolder.getName());
delete this comment

2021-08-04 20:17 UTC, cuibus commented on src/main/java/utcn/repoviewer/MainWindow.java
> +                String studentFileName = Paths.get("src", "main", "students files",
use FeedbackManagement.getStudentFilePath(...) instead of computing the path all over again!

2021-08-04 20:17 UTC, cuibus commented on src/main/java/utcn/repoviewer/MainWindow.java
> +    private File fileN = new File(".");
do we still need this ? If not, delete it!

2021-08-04 20:17 UTC, cuibus commented on src/main/java/utcn/repoviewer/StudentManager.java
> +        /* Message message = new MimeMessage(session);
please remove the comment signs. Commenting this part of the method was just a setup for your machine, so that you can test the program easier.

2021-08-04 20:17 UTC, cuibus commented on src/main/java/utcn/repoviewer/MainWindow.java
> +    // private DefaultListModel<StudentInformation> studentsList = new DefaultListModel<StudentInformation>();
do we still need this ? I think not, please delete it!

2021-08-05 06:54 UTC, adelinb commented on src/main/java/utcn/repoviewer/MainWindow.form
> +        <EventHandler event="stateChanged" listener="javax.swing.event.ChangeListener" parameters="javax.swing.event.ChangeEvent" handler="tabbedPaneOptionsStateChanged"/>
We don't need both. stateChanged is the only one necessary as it will fire every time the tab changes, whereas mouseClicked will fire only when the tab is changed through the mouse. I moved the code inside mouseClicked in stateChanged and it works good.

2021-08-05 07:13 UTC, cuibus approved these changes

2021-08-05 07:13 UTC, merged